<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body shadow">

        <div class="d-flex justify-content-center">
          <img src="img/tt.png" alt="Logo">
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <?php if ($this->view->erroCadastro == true) { ?>
            <ul class="py-2 rounded alert-danger">
                <small><p class="">Erro ao realizar cadastro, verifique se:</p></small>
                <small>
                  <li>A senha deve ter mais de 3 caracteres</li>
                </small>
                <small>
                  <li>O email tem de ser válido</li>
                </small>
                <small>
                  <li>O nome tem de ter mais de 3 caracteres</li>
                </small>
                <small>
                  <li>Verifique se este usuário já existe</li>
                </small>
            </ul>
        <?php } ?>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" class="form-control" placeholder="Nome" name="nome">
              </div>
              
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email'] ?>" class="form-control" placeholder="E-mail" name="email">
              </div>

              <div class="form-group">
                <input type="password" class="form-control" placeholder="Senha" name="senha">
              </div>
              
              <div class="my-3">
                <small class="text-secondary">
                  *Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  